### ISSUE TITLE
No pressure with Genius Mouse Pen M508

### ISSUE THREAD

**Issue by mccouto** [DIGImend/digimend.github.io#7]
I have a Genius Mouse Pen M508 tablet. I use Lubuntu 16.04.3 Kenel 4.10.0-37-generic
The table appears to be normally recognized by Linux but not fully Stylus. The Stylus works like a mouse. When I click on the windows everything works but if I open any file in the programs like Gimp, MyPaint, Krita, even configuring and activating the M508 the Stylus does not draw in open files.
When applying the two lsusb and xinput commands the terminal returned this:

     xinput
    ⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
    ⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
    ⎜   ↳ Dell Dell Universal Receiver            	id=11	[slave  pointer  (2)]
    ⎜   ↳ AlpsPS/2 ALPS GlidePoint                	id=13	[slave  pointer  (2)]
    ⎜   ↳ UC-LOGI  5x8  Tablet                    	id=15	[slave  pointer  (2)]
    ⎜   ↳ UC-LOGI  5x8  Tablet                    	id=16	[slave  pointer  (2)]
    ⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
        ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
        ↳ Video Bus                               	id=6	[slave  keyboard (3)]
        ↳ Power Button                            	id=7	[slave  keyboard (3)]
        ↳ Sleep Button                            	id=8	[slave  keyboard (3)]
        ↳ Integrated_Webcam_1.3M                  	id=9	[slave  keyboard (3)]
        ↳ Dell Dell Universal Receiver            	id=10	[slave  keyboard (3)]
        ↳ AT Translated Set 2 keyboard            	id=12	[slave  keyboard (3)]
        ↳ Dell WMI hotkeys                        	id=14	[slave  keyboard (3)]

    ~$ lsusb
    Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
    Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
    Bus 007 Device 002: ID 5543:0772 UC-Logic Technology Corp. 
    Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
    Bus 006 Device 002: ID 413c:301b Dell Computer Corp. 
    Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
    Bus 001 Device 003: ID 0c45:63ee Microdia 
    Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
    Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
    Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
    Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

It seems that just the stylus needs to work properly under pressure and I can use this tablet day-to-day on Linux.

**Comment by spbnick** [comment]
Moved to DIGImend/digimend-kernel-drivers#80.
